### ISSUE TITLE
atg spliceai conversion fails with gencode and ensembl annotation

### ISSUE THREAD

**Issue by pre-mRNA** [anergictcell/atg#38]
Hi, thanks for writing this package. 

I am trying to use atg to create spliceai tables, and have tested the code using gencode and ensembl annotations: 

```
$ head $gencode 
##description: evidence-based annotation of the human genome (GRCh38), version 39 (Ensembl 105)
##provider: GENCODE
##contact: gencode-help@ebi.ac.uk
##format: gtf
##date: 2021-09-02
chr1    HAVANA  gene    11869   14409   .       +       .       gene_id "ENSG00000223972.5"; gene_type "transcribed_unprocessed_pseudogene"; gene_name "DDX11L1"; level 2; hgnc_id "HGNC:37102"; havana_gene "OTTHUMG00000000961.2";
chr1    HAVANA  transcript      11869   14409   .       +       .       gene_id "ENSG00000223972.5"; transcript_id "ENST00000456328.2"; gene_type "transcribed_unprocessed_pseudogene"; gene_name "DDX11L1"; transcript_type "processed_transcript"; transcript_name "DDX11L1-202"; level 2; transcript_support_level "1"; hgnc_id "HGNC:37102"; tag "basic"; havana_gene "OTTHUMG00000000961.2"; havana_transcript "OTTHUMT00000362751.1";
chr1    HAVANA  exon    11869   12227   .       +       .       gene_id "ENSG00000223972.5"; transcript_id "ENST00000456328.2"; gene_type "transcribed_unprocessed_pseudogene"; gene_name "DDX11L1"; transcript_type "processed_transcript"; transcript_name "DDX11L1-202"; exon_number 1; exon_id "ENSE00002234944.1"; level 2; transcript_support_level "1"; hgnc_id "HGNC:37102"; tag "basic"; havana_gene "OTTHUMG00000000961.2"; havana_transcript "OTTHUMT00000362751.1";
chr1    HAVANA  exon    12613   12721   .       +       .       gene_id "ENSG00000223972.5"; transcript_id "ENST00000456328.2"; gene_type "transcribed_unprocessed_pseudogene"; gene_name "DDX11L1"; transcript_type "processed_transcript"; transcript_name "DDX11L1-202"; exon_number 2; exon_id "ENSE00003582793.1"; level 2; transcript_support_level "1"; hgnc_id "HGNC:37102"; tag "basic"; havana_gene "OTTHUMG00000000961.2"; havana_transcript "OTTHUMT00000362751.1";
chr1    HAVANA  exon    13221   14409   .       +       .       gene_id "ENSG00000223972.5"; transcript_id "ENST00000456328.2"; gene_type "transcribed_unprocessed_pseudogene"; gene_name "DDX11L1"; transcript_type "processed_transcript"; transcript_name "DDX11L1-202"; exon_number 3; exon_id "ENSE00002312635.1"; level 2; transcript_support_level "1"; hgnc_id "HGNC:37102"; tag "basic"; havana_gene "OTTHUMG00000000961.2"; havana_transcript "OTTHUMT00000362751.1";
$ atg -f gtf -t spliceai -i "${gencode}" -o ${wd}/GRCh38-splicing-table.bed -vv
atg: Reading Gtf transcripts from ./genomes/human_genome/gencode/gencode.v39.chr_patch_hapl_scaff.annotation.gtf
Error: ReadWrite error: An error occurred while parsing the GTF input. Please check your input data.
Missing gene_id or transcript_id

Please check `atg --help` for more options
```

I get an identical error with the ensembl annotation. 

The atg command also fails when converting to another format, e.g. refgene. 

Any ideas how to fix this? Thanks a lot.

**Comment by pre-mRNA** [comment]
To note, ATG works fine when I use any of the test .gtf files provided in the repo, so the issue must be related specifically to parsing ensembl and gencode GTFs. 

```
$ atg --from gtf --to refgene --input "./atg/tests/data/NM_001365057.2.gtf" --output "./GCF_000001405.40.refgene"
$ head "./GCF_000001405.40.spliceai.table"
0       NM_001365057.2  chr9    +       74526554        74600974        74526650        74597573        3       74526554,74561921,74597572,     74526752,74562028,74600974,     0       C9orf85 cmpl    cmpl    0,0,2,
```

However, atg still doesn't work, even if I use an alternative gtf file, e.g. 
https://ftp.ncbi.nlm.nih.gov/genomes/all/annotation_releases/9606/GCF_000001405.40-RS_2023_10/GCF_000001405.40_GRCh38.p14_genomic.gtf.gz

```
$ atg --from gtf --to refgene --input "./GCF_000001405.40_GRCh38.p14_genomic.gtf" --output "./GCF_000001405.40.spliceai.table"

Error: ReadWrite error: An error occurred while parsing the GTF input. Please check your input data.
Missing gene_id or transcript_id
```

**Comment by anergictcell** [comment]
Hi @pre-mRNA , thanks for reporting this issue. I checked and can confirm this bug. The reason is that those GTF file contain lines that describe the whole gene (Column 3 is `gene`) These lines do not have a unique `transcript_id` in the attribute column. More info about the format is in the [atg docs](https://docs.rs/atglib/latest/atglib/gtf/index.html) and the [UCSC website](http://genome.ucsc.edu/FAQ/FAQformat.html#format4).

Ideally, ATG should skip those lines, as it cannot interpret them without a unique transcript name. For some reason, I missed that. Fixing this will take me a few days, not sure how much time I have at the moment.

However, in the meantime you can fix the issue yourself, by removing all those `gene` lines from the GTF file:

`grep -v "\tgene\t" GCF_000001405.40_GRCh38.p14_genomic.gtf > fixed_file.gtf`


Alternatively, you can also filter for all lines that contain a `transcript_id` key and remove those that do not have a value:

`grep "transcript_id" GCF_000001405.40_GRCh38.p14_genomic.gtf | grep -v "transcript_id \"\"" > fixed_file.gtf`

**Comment by pre-mRNA** [comment]
Hi, that's completely understandable. Thanks for your quick reply. I've also written a couple of GTF parsers in python and Rust, and the non-standard nature of GTF files can cause terrible headaches. 

Just a quick note, atglib also struggles with the 'five_prime_utr' and 'three_prime_utr' feature type used in ensembl annotations: 

```
$ atg --from gtf --to refgene --input "./Homo_sapiens.GRCh38.110.chr.no-header-no-gene.gtf" --output "./Homo_sapiens.GRCh38.110.chr_spliceai-table.txt"
Error: ReadWrite error: An error occurred while parsing the GTF input. Please check your input data.
invalid feature type five_prime_utr
```

The final command I used to clean up my GTF was: 

```
tail -n +6 $annotation | grep -v "\tgene\t" | grep -v "transcript_id \"\"" | grep -v "gene_id \"\"" | grep "gene_id" | grep "transcript_id" | awk '$3 == "exon" || $3 == "transcript"'  > "${wd}/Homo_sapiens.GRCh38.110.chr.cleaned.gtf"
```

This appears to be compatible with atg's conversions. 

Thanks a lot!

**Comment by anergictcell** [comment]
I reopened the issue, so I can use it for tracking the fix.

About the `five_prime_utr` issue: Where did you get the GTF file from or can you share the file with me? I can fix this as well and would like to have some test cases for it.

**Comment by pre-mRNA** [comment]
Thanks. The 'five_prime_utr' feature was from the [Ensembl 111 GRCh38 release](https://ftp.ensembl.org/pub/release-111/gtf/homo_sapiens/Homo_sapiens.GRCh38.111.chr.gtf.gz).
